project_id = "yavewuildzgbdyfvkwhk"

[functions.google-calendar]
verify_jwt = false

[functions.upload-student-photo]
verify_jwt = false

[functions.upload-photo]
verify_jwt = false

[functions.upload-counseling-attachment]
verify_jwt = false


