project_id = "yavewuildzgbdyfvkwhk"

[functions.upload-student-photo]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.upload-photo]
verify_jwt = false

[functions.upload-counseling-attachment]
verify_jwt = false

[functions.upload-evidence-photo]
verify_jwt = false
